name: better_flutter
description: Let's make beautiful app with Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # beautiful ui and tool
  getwidget: ^3.0.1
  # router and state management
  get: ^4.6.5
  # code viewer
  widget_with_codeview: ^2.0.1+2
  # logger tool
  logger: ^1.1.0
  # markdown viewer
  flutter_markdown: ^0.6.10+5
  package_info_plus: ^1.4.3+1
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.4
  # app闪屏
  flutter_native_splash: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # 生成app各尺寸图标
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - lib/pages/getwidget/components/
    - assets/images/avatar.jpeg
    - assets/images/carousel01.jpeg
    - assets/images/carousel02.jpeg
    - assets/images/carousel03.jpeg
    
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
