import 'package:flutter/material.dart';
import 'package:getwidget_test/components/index.dart';
import 'package:getwidget_test/main.dart';

Map<String, WidgetBuilder> routes = {
  "/": (context) => const MyHomePage(title: "GetWidget Test"),
  "button": (context) => ButtonsPage(),
  "badge": (context) => BadgePage(),
  "avatar": (context) => AvatarPage(),
  "image": (context) => ImagePage(),
  "card": (context) => CardPage(),
  "carousel": (context) => CarouselPage(),
  "tile": (context) => TilePage(),
  "tab": (context) => TabPage(),
  "floating_widget": (context) => FloatingWidgetPage(),
  "toast": (context) => ToastPage(),
  "toggle": (context) => TogglePage(),
  "typo": (context) => TypographyPage(),
  "accordion": (context) => AccordionPage(),
  "alert": (context) => AlertPage(),
  "searchbar": (context) => SearchBarPage(),
  "rating": (context) => RatingPage(),
  "dropdown": (context) => DropdownPage(),
  "loader": (context) => LoaderPage(),
  "progress": (context) => ProgressBarPage(),
  "shimmer": (context) => ShimmerPage(),
  "animation": (context) => AnimationPage(),
  "border": (context) => BorderPage(),
  "bottomsheet": (context) => BottomSheetPage(),
  "checkbox": (context) => CheckboxPage(),
  "checkboxlisttile": (context) => CheckboxListTilePage(),
  "multiselect": (context) => MultiSelectPage(),
  "intro": (context) => IntroPage(),
  "radio": (context) => RadioPage(),
  "radiolisttile": (context) => RadioListTilePage(),
  "stickyheader": (context) => SticktHeaderPage(),
};
